version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - webnet
    env_file:
      - docker.env
    ports:
      - 6379:6379
  main:
    container_name: main
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - docker.env
    networks:
      - webnet
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    command: npm run start:dev
networks:
  webnet:
